<?php

/**
 * @file
 * Component module for sending Mime-encoded emails.
 */

/**
 * Implements mail_post_process().
 */
function mimemail_compress_mail_post_process(&$message, $mailkey) {
  module_load_include('inc', 'mimemail_compress');
  // Separate CSS from HTML for processing.
  $parts = mimemail_compress_clean_message($message);
  // Compress HTML and CSS into combined message.
  if (!empty($parts)) {
    $output = new mimemail_compress($parts['html'], $parts['css']);
    $output = $output->compress();
    $message = $output;
  }
}
